### ISSUE TITLE
Uncaught TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type '...

### ISSUE THREAD

**Issue by sameetsidhu** [kiteco/atom-plugin#560] opened 2019-01-12 15:01 UTC
I was writing the code below from a tutorial (not complete yet) and as I am following along I keep getting this error from the kite package.

```
import numpy as np
import matplotlib.pyplot as plt

pi = np.pi
x = np.linspace(-4 * pi, 4 * pi, 5000)
plt.rcParams.update({'font.size': 20})
plt.rcParams['figure.figsize'] = (12, 5)
plt.axhline(0, color='gray', lw=1)
plt.plot(x, np.sin(x) / x, label=r'$f(x)=\frac{\sin(x)}{x}$')
```

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Education
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.135.0

### Stack Trace

Uncaught TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.

```
At C:\Users\Sameet\.atom\packages\kite\lib\elements\kite-signature.js:55

TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.
    at HTMLElement.connectedCallback (/packages/kite/lib/elements/kite-signature.js:55:25)
    at HTMLElement.disconnectedCallback (/packages/kite/lib/elements/kite-signature.js:25:23)
    at updateChildren (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1131524)
    at patch (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1132153)
    at Object.updateSync (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:126751)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:70218)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:67605)
    at visible.suppressUpdates.updatedSynchronously.updateScheduled.i.getScheduler.updateDocument (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:66633)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:326599)
```

### Commands

```
     -2:45.9.0 editor:newline (input.hidden-input)
     -2:41.3.0 core:backspace (input.hidden-input)
     -1:27.6.0 core:move-left (input.hidden-input)
     -1:20.7.0 autocomplete-plus:activate (atom-text-editor.editor.mini)
     -1:20.1.0 core:backspace (input.hidden-input)
     -1:17.1.0 editor:newline (input.hidden-input)
     -1:09.6.0 autocomplete-plus:activate (atom-text-editor.editor.mini)
     -1:06.8.0 core:backspace (input.hidden-input)
     -1:03.1.0 core:move-right (input.hidden-input)
     -0:54.3.0 editor:newline (input.hidden-input)
  2x -0:50.4.0 autocomplete-plus:activate (atom-text-editor.editor.mini)
     -0:43.7.0 core:backspace (input.hidden-input)
  2x -0:34.1.0 autocomplete-plus:activate (atom-text-editor.editor.mini)
     -0:21.6.0 core:move-right (input.hidden-input)
     -0:14.2.0 core:delete (input.hidden-input)
     -0:11.9.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autocomplete-bibtex 1.2.1 
autocomplete-python 1.11.0 
busy-signal 2.0.0 
dash-syntax 0.4.2 
dash-ui 0.4.4 
file-icons 2.1.27 
Hydrogen 2.7.0 
ide-html 0.5.0 
ide-json 0.2.1 
ide-php 0.7.18 
ide-python 1.2.0 
intentions 1.1.5 
kite 0.135.0 
language-latex 1.2.0 
latex 0.50.2 
linter 2.3.0 
linter-flake8 2.3.0 
linter-ui-default 1.7.1 
pdf-view 0.71.0 
pen-paper-coffee-syntax 0.17.0 
python-indent 1.1.6 
script 3.18.1 
tablr 1.8.3 
typewriter 0.7.1 
wordcount 3.0.0 
```

**Comment by KimByoungmo** [comment] 2019-02-07 15:19
same issue occured in my computer

**Comment by Jiawei-Navican** [comment] 2019-02-13 17:56
same here. lasts for one month. It hasn't been fixed yet.

**Comment by mapettheone** [comment] 2019-02-15 14:37
**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.148.0


### Stack Trace

Uncaught TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.

```
At C:\Users\Kuba\.atom\packages\kite\lib\elements\kite-signature.js:55

TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.
    at HTMLElement.connectedCallback (/packages/kite/lib/elements/kite-signature.js:55:25)
    at HTMLElement.disconnectedCallback (/packages/kite/lib/elements/kite-signature.js:25:23)
    at updateChildren (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1131524)
    at patch (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1132153)
    at Object.updateSync (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:126751)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:70218)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:67605)
    at visible.suppressUpdates.updatedSynchronously.updateScheduled.i.getScheduler.updateDocument (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:66633)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:326599)
```

### Commands

```
     -0:44.1.0 intentions:highlight (input.hidden-input)
     -0:44 core:save (input.hidden-input)
     -0:43.6.0 atom-beautify:beautify-editor (input.hidden-input)
     -0:43.2.0 core:save (input.hidden-input)
     -0:42.9.0 script:run (input.hidden-input)
  6x -0:41.4.0 core:backspace (input.hidden-input)
     -0:39.4.0 intentions:highlight (input.hidden-input)
     -0:39.3.0 core:save (input.hidden-input)
     -0:38.8.0 atom-beautify:beautify-editor (input.hidden-input)
     -0:38.5.0 core:save (input.hidden-input)
  3x -0:38.2.0 script:run (input.hidden-input)
  2x -0:35.7.0 core:undo (input.hidden-input)
     -0:35.1.0 core:save (input.hidden-input)
     -0:34.7.0 atom-beautify:beautify-editor (input.hidden-input)
     -0:34.5.0 core:save (input.hidden-input)
     -0:34.2.0 script:run (input.hidden-input)
```

### Non-Core Packages

```
Atom-Bash-Snippets 0.0.3 
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-python-run 0.9.7 
atom-python-virtualenv 1.0.2 
autocomplete-bash-builtins 0.3.5 
autocomplete-python 1.12.0 
bracket-colorizer 1.2.0 
busy-signal 2.0.0 
file-icons 2.1.29 
Hydrogen 2.8.0 
ide-python 1.2.1 
intentions 1.1.5 
kite 0.148.0 
linter 2.3.0 
linter-checkbashisms 0.1.5 
linter-pycodestyle 2.1.3 
linter-pylint 2.1.1 
linter-ui-default 1.7.1 
minimap 4.29.9 
multi-cursor 2.1.5 
platformio-ide-terminal 2.9.0 
python-autopep8 0.1.3 
python-debugger 0.2.0 
python-indent 1.1.7 
python-isort 0.0.7 
python-tools 0.6.9 
refactor 0.11.5 
script 3.18.1 
sort-lines 0.18.0 
wakatime 7.0.7 
```

`

**Comment by QRQaccount** [comment] 2019-02-16 07:24
same issue occured in my computer...

**Comment by j0rdnh** [comment] 2019-02-16 23:50
same thing for me too

**Comment by its-dhung** [comment] 2019-02-20 01:18
Hi guys, sorry for the delay. We're looking into a fix for this. We think it's caused by a conflict with the `atom-ide-ui` package.

**Comment by mattiasarro** [comment] 2019-02-20 09:54
@its-dhung I have the issue with a fresh Kite installation and no `atom-ide-ui` package.

![screen shot 2019-02-20 at 09 51 59](https://user-images.githubusercontent.com/53719/53082705-53daf080-34f5-11e9-8e70-743ba155da75.png)

**Closed** 2019-03-05 16:48 UTC
