### ISSUE TITLE
Sidebar is blank

### ISSUE THREAD

**Issue by kuno** [kiteco/atom-plugin#161] opened 2017-04-07 12:32 UTC
Hi:
  New to here.
  I installed the kite.app and plugin for atom, everything seems works fine except the sidebar for atom edit is blank leave only kite logo sets in the middle of the sidebar.

  Is this normal behavior ?

**Comment by abe33** [comment] 2017-04-07 16:24
Hi @kuno, do you see an error in Atom's devtools console?

**Comment by kuno** [comment] 2017-04-08 00:13
yes, There are a lot of errors like this 

```log
data-loader.js:126 Error: Error 408: timed out waiting for completions


    at promisifyReadResponse.then.data (/Users/kuno/.atom/packages/kite/lib/data-loader.js:103:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

```log
data-loader.js:204 Uncaught (in promise) Error: 410 status at /api/buffer/atom/:Users:kuno:Works:github:kuno:Coding-the-Matrix:Week5-Dimension:Dimension_Problems:Dimension_problems.py/da235f635a8c1128e2ba7cad2fd2f835/tokens?localtoken=q7UKk963url4lzbCx5vPkWXlGRYRyxH5UUpVNGMA71VbRxjSY4gnWyNKuHngB-G9WnrgHl8Yua0T_b0xwz5xiA
    at promisifyRequest.then.resp (/Users/kuno/.atom/packages/kite/lib/data-loader.js:204:15)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by jlozano** [comment] 2017-06-01 22:33
@kuno are you still experiencing this issue?

**Comment by OGKevin** [comment] 2017-06-02 06:44
@jlozano I am still experiencing this issue

**Comment by OGKevin** [comment] 2017-06-04 17:57
Is there any news on this issue ❓

**Comment by jlozano** [comment] 2017-06-07 06:11
@abe33 any ideas?

**Comment by OGKevin** [comment] 2017-06-07 10:36
Im happy to help with data collection if needed 😊

**Comment by abe33** [comment] 2017-06-07 14:15
@jlozano I'm not really sure, if we get a 404 from the hover endpoint it means that there's a token at the given position (because otherwise we wouldn't make the request), but somehow kited doesn't find the corresponding token. 

@OGKevin by change, is your file containing unicode characters or has a specific encoding? That might be a clue as we could end up computing an invalid offset.

**Comment by OGKevin** [comment] 2017-06-07 14:33
@abe33 wel the side bar is empty no matter what file I open it on. In non of my files I've used  unicode characters. Im getting 410 and 408.

```traceback
/Users/KevinH/.atom/packages/kite/lib/data-loader.js:216 Error: Error 410: error getting callee from backend: &{%!s(*http.body=&{0xc424aef420 <nil> <nil> false false {0 0} false false false <nil>}) {%!s(int32=0) %!s(uint32=0)} %!s(bool=false) <nil> %!s(func(error) error=0x104cba9d0) %!s(func() error=0x104cba960)}


    at promisifyReadResponse.then.data (/Users/KevinH/.atom/packages/kite/lib/data-loader.js:209:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

```traceback
/Users/KevinH/.atom/packages/kite/lib/data-loader.js:150 Error: Error 408: timed out waiting for completions


    at promisifyReadResponse.then.data (/Users/KevinH/.atom/packages/kite/lib/data-loader.js:126:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
Im using UTF-8

All my code can be found here: [OGKevin/ComBunqWebApp](https://github.com/OGKevin/ComBunqWebApp)

**Comment by abe33** [comment] 2017-06-07 16:00
I'm cloning your project to see if I can reproduce.

**Comment by abe33** [comment] 2017-06-07 16:33
Last question, which version of Atom are you running? I noticed that on 1.19 (dev version) the computation of the mouse position is broken when the editor is scrolled. Other than that, it works well for me on 1.17 and 1.18 beta within your project.

![kite-hover](https://user-images.githubusercontent.com/247140/26889836-b72d31d8-4baf-11e7-9d48-efa12ab958ad.gif)

**Comment by OGKevin** [comment] 2017-06-07 18:26
@abe33 😑 I feel really stupid now. The kite sidebar (not the atom plug in) updates automatically as you write. As for this plugin one must specifically ask for the plugin side bar to show the info 😕. Sorry if this is obvious 🙈.

The sidebar works as intended, meaning when you open it, it is blank until you specifically press `more`

**Comment by abe33** [comment] 2017-06-08 13:02
ok cool :) I was starting to get nervous for not understanding the root cause. Can I close this issue then?

**Comment by OGKevin** [comment] 2017-06-08 13:46
@abe33 yep i think this issue can be closed 😊 👍

**Comment by abe33** [comment] 2017-06-08 14:17
Thanks for the responsive feedback! Closing it now.

**Closed by abe33** 2017-06-08 14:17 UTC
