### ISSUE TITLE
Unistalling kite hangs Atom

### ISSUE THREAD

**Issue by louspringer** [kiteco/atom-plugin#206] opened 2017-06-09 20:14 UTC
Uninstall of the kite executable renders atom useless. Atom hangs forever with kite plugin trying to connect to kite daemon.

**Comment by abe33** [comment] 2017-06-13 10:39
Hi @louspringer, 

That's weird, given that all communication with the daemon is made asynchronously, it should not lock the UI, can you details in which context it affect Atom responsiveness? Do you have some kind of reproductions steps I could use to reproduce your issue?

**Comment by jansorg** [comment] 2018-03-14 17:06
Closing due to missing feedback. I wasn't able to reproduce with the current versions of Kite and the plugin.

**Closed by jansorg** 2018-03-14 17:06 UTC
Labels: bug
