### ISSUE TITLE
Kite not detecting that atom is installed

### ISSUE THREAD

**Issue by Yu-w** [kiteco/atom-plugin#255] opened 2017-10-01 05:36 UTC
Hi,

I have both Kite app and plugin for atom installed; however, it doesn't seem that Kite has detected that atom is installed and available to use.

I am using macOS Sierra 10.12.6 with Atom 1.20.1.

It always fail without any message when trying to install Kite engine from the kite icon on status bar.
![image](https://user-images.githubusercontent.com/8606935/31052100-2b27bdd4-a640-11e7-8b7e-9d0f9e904ec6.png)
![image](https://user-images.githubusercontent.com/8606935/31052102-33645c96-a640-11e7-9fd6-ba368004a2b2.png)

And atom is not appearing on plugin section of local settings page.
![image](https://user-images.githubusercontent.com/8606935/31052107-44dbf7cc-a640-11e7-9c57-a88795297357.png)

Error messages in the atom's console:
![image](https://user-images.githubusercontent.com/8606935/31052161-98f20148-a641-11e7-822f-0f8c16ba825c.png)

Need help!!! Thanks!
Yu

**Comment by abe33** [comment] 2017-10-02 09:04
Hi @Yu-w, sorry to hear about that, can you tell me if the command `mdfind kMDItemCFBundleIdentifier = "com.kite.Kite"` gives you some results in your terminal, this is the command we're using to detect your kite installation. It should return a list with at least one path to the Kite executable.

**Comment by Yu-w** [comment] 2017-10-02 21:45
Thanks for following up!
You mean run the command on terminal?
I got nothing...
![image](https://user-images.githubusercontent.com/8606935/31100947-10a00a5a-a791-11e7-8076-b74bf5b90702.png)

**Comment by abe33** [comment] 2017-10-03 08:39
@Yu-w, that's quite weird, I'll try to reproduce that, some more questions if you mind: 
- Did you tried to [install Kite from the website](https://kite.com/download) manually?
- When trying to install it from Atom, did you see an error in the console?

**Comment by Yu-w** [comment] 2017-10-03 15:43
• Yes, I tried, not detecting atom as well.
• Here's the console after I uninstall and then re-install Kite from Atom:
![image](https://user-images.githubusercontent.com/8606935/31134389-8cb56536-a827-11e7-98b8-46e8b6ffe07a.png)

**Comment by Yu-w** [comment] 2017-10-03 15:46
And here's the error log as I then tried to click `install Kite` from the lower-right kite icon from bottom status bar:
![image](https://user-images.githubusercontent.com/8606935/31134560-0a08250a-a828-11e7-8e87-383e2cd008c4.png)

It hangs at `Installing Kite` forever.
![image](https://user-images.githubusercontent.com/8606935/31134586-1f6182a2-a828-11e7-94ff-e15bf313d26d.png)

**Comment by jansorg** [comment] 2018-02-06 17:37
@Yu-w There have been several fixes around this feature. Could you try again with the current versions of Kite and the plugin?

**Comment by jansorg** [comment] 2018-03-14 17:11
Closing due to missing feedback.

**Closed by jansorg** 2018-03-14 17:11 UTC
